# Generated by Django 3.1.7 on 2021-03-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='example', max_length=128),
            preserve_default=False,
        ),
    ]
