# Generated by Django 3.1.7 on 2021-03-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='banner_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
