# Generated by Django 3.1.7 on 2021-03-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20210321_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description', max_length=512),
            preserve_default=False,
        ),
    ]
